name: temporal
base: core24
adopt-info: temporal-cli
grade: stable
confinement: strict
compression: lzo
summary: Use the CLI to run a Temporal Server and interact with it
description: |
  Temporal is a distributed, scalable, durable, and highly available orchestration
  engine used to execute asynchronous, long-running business logic in a scalable
  and resilient way.

  This is temporal-cli, which can be used to run a Temporal Server and interact with it.

apps:
  temporal:
    command: bin/temporal
    plugs:
      - home
      - network-bind

parts:
  temporal-cli:
    plugin: go
    source: https://github.com/temporalio/cli.git
    source-tag: "v1.1.2"
    build-snaps:
      - go
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | sed "s/^v//")
    prime:
      - bin/temporal
